apiVersion: batch/v1
kind: CronJob
metadata:
  name: billing-job
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: billing-job
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: cronjob
    app.kubernetes.io/component: run
    carto.run/workload-name: billing-job
spec:
  schedule: 0 15 * * ?
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: billing-job
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: cronjob
        carto.run/workload-name: billing-job
        conventions.carto.run/framework: spring-boot
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            boot.spring.io/version: 3.0.5
            conventions.carto.run/applied-conventions: |-
              appliveview-sample/app-live-view-appflavour-check
              inspect-image-convention/buildpacks
              inspect-image-convention/base-image
              inspect-image-convention/run-image
              inspect-image-convention/source
              spring-boot-convention/auto-configure-actuators-check
              spring-boot-convention/spring-boot
              spring-boot-convention/app-live-view-appflavour-check
            developer.conventions/target-containers: workload
            inspect-image.buildpacks.io/base-image: |-
              reference: ghcr.io/making/build-service@sha256:4ad9babcb718243b0dbdb29e8b3e1d474eafd6edc20e73a2a09dfde213d5fdcf
              top_layer: sha256:2dccd34d83ce1fcec8a5f20f06f0963d059264297222d1480a70c0d6645c88a1
            inspect-image.buildpacks.io/buildpacks: |-
              - id: paketo-buildpacks/ca-certificates
                version: 3.6.0
              - id: paketo-buildpacks/bellsoft-liberica
                version: 9.11.0
              - id: paketo-buildpacks/syft
                version: 1.10.1
              - id: paketo-buildpacks/maven
                version: 6.13.0
              - id: paketo-buildpacks/executable-jar
                version: 6.6.2
              - id: paketo-buildpacks/apache-tomcat
                version: 7.12.1
              - id: paketo-buildpacks/liberty
                version: 3.5.0
              - id: paketo-buildpacks/dist-zip
                version: 5.5.2
              - id: paketo-buildpacks/spring-boot
                version: 5.23.0
              - id: paketo-buildpacks/image-labels
                version: 4.4.1
            inspect-image.buildpacks.io/run-image: ghcr.io/making/build-service@sha256:4ad9babcb718243b0dbdb29e8b3e1d474eafd6edc20e73a2a09dfde213d5fdcf
            inspect-image.opencontainers.org/source: master/300868fc3b7fb6d6eed668c862b82fc9d3f23ede
          labels:
            app.kubernetes.io/component: run
            app.kubernetes.io/part-of: billing-job
            apps.tanzu.vmware.com/has-tests: "true"
            apps.tanzu.vmware.com/workload-type: cronjob
            carto.run/workload-name: billing-job
            conventions.carto.run/framework: spring-boot
        spec:
          containers:
          - env:
            - name: BPL_JVM_THREAD_COUNT
              value: "8"
            image: ghcr.io/making/supply-chain/billing-job-demo@sha256:7b6b114555a97d7ec5a6127a1006789b3904d6a280c7096e2eecd2cd2b6a5275
            name: workload
            resources: {}
            securityContext:
              runAsUser: 1000
          serviceAccountName: default
          restartPolicy: Never

