apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: rest-service
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: rest-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: rest-service
spec:
  type: openapi
  description: simple rest api.
  system: dev
  owner: playground
  location:
    path: /v3/api-docs
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: rest-service

