apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-api
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: blog-api
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1673001989096365132"
    kapp.k14s.io/association: v1.eae2bf111fb39e9481c024f683deba7a
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 3.0.1
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/spring-boot-actuator-probes
          spring-boot-convention/service-intent-postgres
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-boot
          appliveview-sample/app-live-view-appflavours-boot
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        kapp.k14s.io/disable-original: ""
        kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-api;carto.run/v1alpha1
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
        services.conventions.apps.tanzu.vmware.com/postgres: postgresql/42.5.1
      labels:
        apis.apps.tanzu.vmware.com/register-api: "true"
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blog-api
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: blog-api
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        kapp.k14s.io/app: "1673001989096365132"
        kapp.k14s.io/association: v1.eae2bf111fb39e9481c024f683deba7a
        services.conventions.apps.tanzu.vmware.com/postgres: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: blog-api
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -XX:ReservedCodeCacheSize=32M -Xss512k -Dfile.encoding="UTF-8" -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s" -Duser.country="JP" -Duser.language="ja" -Duser.timezone="Asia/Tokyo"
        - name: BPL_JVM_THREAD_COUNT
          value: "28"
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            secretKeyRef:
              key: otel-trace-service-name
              name: otel-config
        - name: SPRING_DATASOURCE_HIKARI_DATASOURCEPROPERTIES_SSLFACTORY
          value: org.postgresql.ssl.DefaultJavaSSLFactory
        - name: MANAGEMENT_TRACING_PROPAGATION_TYPE
          value: B3
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: blog-config
        - name: BLOG_TENANT_USERS_0
          valueFrom:
            secretKeyRef:
              key: users-0
              name: blog-config
        - name: BLOG_TENANT_USERS_1
          valueFrom:
            secretKeyRef:
              key: users-1
              name: blog-config
        - name: BLOG_TENANT_USERS_2
          valueFrom:
            secretKeyRef:
              key: users-2
              name: blog-config
        - name: BLOG_GITHUB_CONTENTOWNER
          value: making
        - name: BLOG_GITHUB_CONTENTREPO
          value: blog.ik.am
        - name: BLOG_GITHUB_ACCESSTOKEN
          valueFrom:
            secretKeyRef:
              key: github-access-token
              name: blog-config
        - name: BLOG_GITHUB_WEBHOOKSECRET
          valueFrom:
            secretKeyRef:
              key: github-webhook-secret
              name: blog-config
        - name: BLOG_GITHUB_TENANTS_EN_CONTENTOWNER
          value: making
        - name: BLOG_GITHUB_TENANTS_EN_CONTENTREPO
          value: ik.am_en
        - name: BLOG_GITHUB_TENANTS_EN_ACCESSTOKEN
          valueFrom:
            secretKeyRef:
              key: github-access-token-en
              name: blog-config
        - name: BLOG_GITHUB_TENANTS_EN_WEBHOOKSECRET
          valueFrom:
            secretKeyRef:
              key: github-webhook-secret-en
              name: blog-config
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: otel-trace-endpoint
              name: otel-config
        - name: MANAGEMENT_METRICS_TAGS_JAVA_VERSION
          value: ${java.version}
        - name: INFO_ENV_HOSTNAME
          value: ${HOSTNAME}
        - name: INFO_ENV_K_SERVICE
          value: ${K_SERVICE}
        - name: INFO_ENV_K_CONFIGURATION
          value: ${K_CONFIGURATION}
        - name: INFO_ENV_K_REVISION
          value: ${K_REVISION}
        image: ghcr.io/making/supply-chain/blog-api-blog@sha256:e36a4e8f39a0f967a31a663ad209ccc62187cee1f965825f956eb8af18d8c723
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

