apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-api
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: blog-api
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1665663307561447397"
    kapp.k14s.io/association: v1.eae2bf111fb39e9481c024f683deba7a
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 3.0.0-RC1
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/service-intent-postgres
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-boot
          appliveview-sample/app-live-view-appflavours-boot
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/making/build-service@sha256:f8dbbf8fa654c1731e039671a6683b97d3e4a2cd8344e9e99409cad8ecaf5f95
          top_layer: sha256:d10fcfd222e42332f995be30faf8856758b34ce68e864bf2206d87bf3f1a7108
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/deprecation-warnings
            version: 0.0.2
          - id: paketo-buildpacks/ca-certificates
            version: 3.4.0
          - id: paketo-buildpacks/bellsoft-liberica
            version: 9.8.0
          - id: paketo-buildpacks/syft
            version: 1.10.1
          - id: paketo-buildpacks/maven
            version: 6.8.0
          - id: paketo-buildpacks/executable-jar
            version: 6.5.0
          - id: paketo-buildpacks/apache-tomcat
            version: 7.6.0
          - id: paketo-buildpacks/apache-tomee
            version: 1.3.0
          - id: paketo-buildpacks/liberty
            version: 2.2.0
          - id: paketo-buildpacks/dist-zip
            version: 5.4.0
          - id: paketo-buildpacks/spring-boot
            version: 5.19.0
          - id: paketo-buildpacks/image-labels
            version: 4.3.0
        inspect-image.buildpacks.io/run-image: ghcr.io/making/build-service@sha256:f8dbbf8fa654c1731e039671a6683b97d3e4a2cd8344e9e99409cad8ecaf5f95
        inspect-image.opencontainers.org/source: main/cf9359b53ca76354e2d96bf5509cf5b98babdb62
        kapp.k14s.io/disable-original: ""
        kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-api;carto.run/v1alpha1
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
        services.conventions.apps.tanzu.vmware.com/postgres: postgresql/42.5.0
      labels:
        apis.apps.tanzu.vmware.com/register-api: "true"
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blog-api
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: blog-api
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        kapp.k14s.io/app: "1665663307561447397"
        kapp.k14s.io/association: v1.eae2bf111fb39e9481c024f683deba7a
        services.conventions.apps.tanzu.vmware.com/postgres: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: blog-api
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -XX:ReservedCodeCacheSize=32M -Xss512k -Dfile.encoding="UTF-8" -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s" -Duser.country="JP" -Duser.language="ja" -Duser.timezone="Asia/Tokyo"
        - name: BPL_JVM_THREAD_COUNT
          value: "28"
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            secretKeyRef:
              key: otel-trace-service-name
              name: otel-config
        - name: SPRING_DATASOURCE_HIKARI_DATASOURCEPROPERTIES_SSLFACTORY
          value: org.postgresql.ssl.DefaultJavaSSLFactory
        - name: BLOG_GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: github-access-token
              name: blog-config
        - name: BLOG_GITHUB_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: github-webhook-secret
              name: blog-config
        - name: MANAGEMENT_OTLP_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: otel-trace-endpoint
              name: otel-config
        - name: MANAGEMENT_OTLP_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              key: otel-trace-username
              name: otel-config
        - name: MANAGEMENT_OTLP_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: otel-trace-password
              name: otel-config
        - name: MANAGEMENT_METRICS_TAGS_JAVA_VERSION
          value: ${java.version}
        - name: INFO_ENV_HOSTNAME
          value: ${HOSTNAME}
        - name: INFO_ENV_K_SERVICE
          value: ${K_SERVICE}
        - name: INFO_ENV_K_CONFIGURATION
          value: ${K_CONFIGURATION}
        - name: INFO_ENV_K_REVISION
          value: ${K_REVISION}
        image: ghcr.io/making/supply-chain/blog-api-blog@sha256:0b61c68ef9c2df383fddab9f714bb975ad7cb54366a888fff6667b9d456c0130
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 320Mi
          requests:
            memory: 320Mi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

