
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: #@ data.values.workload.metadata.name
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 500Mi

