#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"apiVersion": "serving.knative.dev/v1", "kind": "Service"})
---
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
