apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: blog-api-blog-db
  annotations:
    kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-api;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"blog-api","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1660936442515730218","kapp.k14s.io/association":"v1.eae2bf111fb39e9481c024f683deba7a"},"name":"blog-api","namespace":"blog"},"spec":{"env":[{"name":"JAVA_TOOL_OPTIONS","value":"-XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Dfile.encoding=UTF-8"},{"name":"BPL_JVM_THREAD_COUNT","value":"28"},{"name":"SPRING_RSOCKET_SERVER_FRAGMENTSIZE","value":"16MB"},{"name":"SPRING_PROFILES_ACTIVE","value":"kubernetes"},{"name":"BLOG_GITHUB_ACCESS_TOKEN","valueFrom":{"secretKeyRef":{"key":"github-access-token","name":"blog-config"}}},{"name":"BLOG_GITHUB_WEBHOOK_SECRET","valueFrom":{"secretKeyRef":{"key":"github-webhook-secret","name":"blog-config"}}},{"name":"MANAGEMENT_ENDPOINT_HEAPDUMP_ENABLED","value":"false"},{"name":"MANAGEMENT_ENDPOINT_THREADDUMP_ENABLED","value":"false"},{"name":"MANAGEMENT_METRICS_TAGS_SPRING_BOOT_VERSION","value":"${info.maven.versions.spring-boot}"},{"name":"MANAGEMENT_METRICS_TAGS_JAVA_VERSION","value":"${java.version}"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1","prometheus.io/path":"/actuator/prometheus","prometheus.io/port":"8081","prometheus.io/scrape":"true"}},{"name":"gitops_branch","value":"mango"},{"name":"gitops_commit_message","value":"Bump"},{"name":"gitops_server_address","value":"https://github.com"},{"name":"gitops_repository_owner","value":"categolj"},{"name":"gitops_repository_name","value":"tap-gitops"},{"name":"gitops_user_email","value":"makingx+bot@gmail.com"},{"name":"gitops_user_name","value":"blog-bot"},{"name":"gitops_ssh_secret","value":"git-basic"},{"name":"clusterBuilder","value":"java-otel"}],"resources":{"limits":{"memory":"256Mi"},"requests":{"memory":"256Mi"}},"serviceClaims":[{"name":"blog-db","ref":{"apiVersion":"v1","kind":"Secret","name":"blog-db"}},{"name":"blog-db-tls-ca","ref":{"apiVersion":"v1","kind":"Secret","name":"blog-db-tls-ca-bindable"}}],"source":{"git":{"ref":{"branch":"rsocket"},"url":"https://github.com/categolj/blog-api"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
    autoscaling.knative.dev/minScale: "1"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: blog-api
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1660936442515730218"
    kapp.k14s.io/association: v1.eae2bf111fb39e9481c024f683deba7a
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-api
spec:
  name: blog-db
  service:
    apiVersion: v1
    kind: Secret
    name: blog-db
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: blog-api
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: blog-api-blog-db-tls-ca
  annotations:
    kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-api;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"blog-api","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1660936442515730218","kapp.k14s.io/association":"v1.eae2bf111fb39e9481c024f683deba7a"},"name":"blog-api","namespace":"blog"},"spec":{"env":[{"name":"JAVA_TOOL_OPTIONS","value":"-XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Dfile.encoding=UTF-8"},{"name":"BPL_JVM_THREAD_COUNT","value":"28"},{"name":"SPRING_RSOCKET_SERVER_FRAGMENTSIZE","value":"16MB"},{"name":"SPRING_PROFILES_ACTIVE","value":"kubernetes"},{"name":"BLOG_GITHUB_ACCESS_TOKEN","valueFrom":{"secretKeyRef":{"key":"github-access-token","name":"blog-config"}}},{"name":"BLOG_GITHUB_WEBHOOK_SECRET","valueFrom":{"secretKeyRef":{"key":"github-webhook-secret","name":"blog-config"}}},{"name":"MANAGEMENT_ENDPOINT_HEAPDUMP_ENABLED","value":"false"},{"name":"MANAGEMENT_ENDPOINT_THREADDUMP_ENABLED","value":"false"},{"name":"MANAGEMENT_METRICS_TAGS_SPRING_BOOT_VERSION","value":"${info.maven.versions.spring-boot}"},{"name":"MANAGEMENT_METRICS_TAGS_JAVA_VERSION","value":"${java.version}"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1","prometheus.io/path":"/actuator/prometheus","prometheus.io/port":"8081","prometheus.io/scrape":"true"}},{"name":"gitops_branch","value":"mango"},{"name":"gitops_commit_message","value":"Bump"},{"name":"gitops_server_address","value":"https://github.com"},{"name":"gitops_repository_owner","value":"categolj"},{"name":"gitops_repository_name","value":"tap-gitops"},{"name":"gitops_user_email","value":"makingx+bot@gmail.com"},{"name":"gitops_user_name","value":"blog-bot"},{"name":"gitops_ssh_secret","value":"git-basic"},{"name":"clusterBuilder","value":"java-otel"}],"resources":{"limits":{"memory":"256Mi"},"requests":{"memory":"256Mi"}},"serviceClaims":[{"name":"blog-db","ref":{"apiVersion":"v1","kind":"Secret","name":"blog-db"}},{"name":"blog-db-tls-ca","ref":{"apiVersion":"v1","kind":"Secret","name":"blog-db-tls-ca-bindable"}}],"source":{"git":{"ref":{"branch":"rsocket"},"url":"https://github.com/categolj/blog-api"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
    autoscaling.knative.dev/minScale: "1"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: blog-api
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1660936442515730218"
    kapp.k14s.io/association: v1.eae2bf111fb39e9481c024f683deba7a
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-api
spec:
  name: blog-db-tls-ca
  service:
    apiVersion: v1
    kind: Secret
    name: blog-db-tls-ca-bindable
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: blog-api

