apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: blog-api-blog-db
  annotations:
    kapp.k14s.io/disable-original: ""
    kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-api;carto.run/v1alpha1
    autoscaling.knative.dev/minScale: "1"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: blog-api
    apps.jaguchi.maki.lol/test-type: maven-jdk-17
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1660936442515730218"
    kapp.k14s.io/association: v1.eae2bf111fb39e9481c024f683deba7a
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-api
spec:
  name: blog-db
  service:
    apiVersion: v1
    kind: Secret
    name: blog-db
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: blog-api
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: blog-api-blog-db-tls-ca
  annotations:
    kapp.k14s.io/disable-original: ""
    kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-api;carto.run/v1alpha1
    autoscaling.knative.dev/minScale: "1"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: blog-api
    apps.jaguchi.maki.lol/test-type: maven-jdk-17
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1660936442515730218"
    kapp.k14s.io/association: v1.eae2bf111fb39e9481c024f683deba7a
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-api
spec:
  name: blog-db-tls-ca
  service:
    apiVersion: v1
    kind: Secret
    name: blog-db-tls-ca-bindable
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: blog-api

