apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: plantuml
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: plantuml
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: plantuml
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: ghcr.io/making/sources:latest?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/making/tanzu-application-platform/full-deps-package-repo@sha256:b0efa340004613e96fc63586df6959d1917de25945bd9eded7fbb1a81c6caf89
          top_layer: sha256:1d694ab175cfdbd2209c819d0c4fcfdf0217c05451aeca28682ac3295f0fd3ff
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/ca-certificates
            version: 3.6.7
          - id: tanzu-buildpacks/bellsoft-liberica
            version: 9.13.0
          - id: paketo-buildpacks/syft
            version: 1.10.1
          - id: tanzu-buildpacks/executable-jar
            version: 6.8.3
          - id: tanzu-buildpacks/dist-zip
            version: 5.6.8
          - id: tanzu-buildpacks/spring-boot
            version: 5.27.6
          - id: tanzu-buildpacks/image-labels
            version: 4.5.6
        inspect-image.buildpacks.io/run-image: ghcr.io/making/tanzu-application-platform/full-deps-package-repo@sha256:e9ba2230f5dfcd8bebc81912660dccb667e43e29e21c00eeae59ed37c746d6d4
        inspect-image.opencontainers.org/source: ghcr.io/making/sources:latest@sha256:35e3dafbace4e4dbb9849b55a4f91938cc6be7b3039527868f3bbd877359badb
        instrumentation.opentelemetry.io/inject-java: opentelemetry/default
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: plantuml
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: plantuml
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/plantuml-demo@sha256:cb604742ed247b0ae23503bb9944b05d7ad4e95e422b60715f56266afe1c9d48
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

