apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: note
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=note"
spec:
  type: service
  lifecycle: experimental
  owner: tmaki@vmware.com
