apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-ui
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: blog-ui
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1672995247146136642"
    kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/making/tanzu-application-platform/full-deps-package-repo@sha256:2ae5423e181301f26fdc8fd383536fcd9089e832ecd4a4b6fd3b84395220f92d
          top_layer: sha256:036693f5e0732223694e7b46c634d0b7cbe69314efa1c4cae17982011f24e9fc
        inspect-image.buildpacks.io/buildpacks: |-
          - id: paketo-buildpacks/ca-certificates
            version: 3.6.1
          - id: tanzu-buildpacks/node-engine
            version: 1.5.2
          - id: tanzu-buildpacks/yarn
            version: 1.1.8
          - id: tanzu-buildpacks/yarn-install
            version: 1.1.2
          - id: tanzu-buildpacks/node-module-bom
            version: 0.3.4
          - id: tanzu-buildpacks/node-run-script
            version: 1.0.8
          - id: tanzu-buildpacks/yarn-start
            version: 1.0.9
          - id: paketo-buildpacks/image-labels
            version: 4.5.0
        inspect-image.buildpacks.io/run-image: ghcr.io/making/tanzu-application-platform/full-deps-package-repo@sha256:2ae5423e181301f26fdc8fd383536fcd9089e832ecd4a4b6fd3b84395220f92d
        inspect-image.opencontainers.org/source: main@sha1:c7f616356261c35e533818a63a55b1b39e1113e4
        kapp.k14s.io/disable-original: ""
        kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-ui;carto.run/v1alpha1
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blog-ui
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: blog-ui
        kapp.k14s.io/app: "1672995247146136642"
        kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/blog-ui-blog@sha256:1b356959c5bfedb524b6dc7e1cdbff3026f911ccabdccbb8fd83f3c611cb6294
        livenessProbe:
          httpGet:
            path: /aboutme
            port: 8080
            scheme: HTTP
        name: workload
        readinessProbe:
          httpGet:
            path: /aboutme
            port: 8080
            scheme: HTTP
          successThreshold: 1
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

