apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-ui
  labels:
    app.kubernetes.io/part-of: blog-ui
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1660936432312369669"
    kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/jaguchi/build-service@sha256:ec6b4df5da0d22786a15a64540a7d6465193f59ac3d4eb707c06dd29d0874933
          top_layer: sha256:68affdc487c70ce84b41688af2adb80bcc9b3185125848dc18d8aaae29ba142c
        inspect-image.buildpacks.io/buildpacks: |-
          - id: paketo-buildpacks/ca-certificates
            version: 3.2.3
          - id: tanzu-buildpacks/node-engine
            version: 0.9.2
          - id: tanzu-buildpacks/yarn
            version: 0.4.1
          - id: tanzu-buildpacks/yarn-install
            version: 0.5.0
          - id: tanzu-buildpacks/node-module-bom
            version: 0.1.8
          - id: tanzu-buildpacks/node-run-script
            version: 0.2.5
          - id: tanzu-buildpacks/yarn-start
            version: 0.3.0
          - id: paketo-buildpacks/image-labels
            version: 4.1.2
        inspect-image.buildpacks.io/run-image: ghcr.io/jaguchi/build-service@sha256:ec6b4df5da0d22786a15a64540a7d6465193f59ac3d4eb707c06dd29d0874933
        kapp.k14s.io/disable-original: ""
        kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-ui;carto.run/v1alpha1
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blog-ui
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: blog-ui
        kapp.k14s.io/app: "1660936432312369669"
        kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    spec:
      containers:
      - image: ghcr.io/jaguchi/blog-ui-blog@sha256:3cbb898746695844cf49236796af06c777e46ae67e7f7ac3ad7c2f53487968b0
        name: workload
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

