apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-ui
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: blog-ui
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1672995247146136642"
    kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/making/build-service@sha256:2102b927cd48b53fb4f438c374087280601ac60f877eeb61ef519effa358723b
          top_layer: sha256:dbf57a4163eceb8bfb3b1301b8bb9d0015be22af50a072e9ca7f6094e423ac8a
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/deprecation-warnings
            version: 0.0.2
          - id: paketo-buildpacks/ca-certificates
            version: 3.4.0
          - id: tanzu-buildpacks/node-engine-lite
            version: 0.16.0
          - id: tanzu-buildpacks/yarn-lite
            version: 0.6.5
          - id: tanzu-buildpacks/yarn-install
            version: 0.7.9
          - id: tanzu-buildpacks/node-module-bom-lite
            version: 0.3.3
          - id: tanzu-buildpacks/node-run-script
            version: 0.4.2
          - id: tanzu-buildpacks/yarn-start
            version: 0.3.6
          - id: paketo-buildpacks/image-labels
            version: 4.3.0
        inspect-image.buildpacks.io/run-image: ghcr.io/making/build-service@sha256:87d92d68b7f5c4c22da6985947e585dc95346898adf82c2c3708dd0ef7a9bef3
        inspect-image.opencontainers.org/source: main/5604f8d5ad092859e4dc3cbc80bfa543d4ab7fb0
        kapp.k14s.io/disable-original: ""
        kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-ui;carto.run/v1alpha1
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blog-ui
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: blog-ui
        kapp.k14s.io/app: "1672995247146136642"
        kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/blog-ui-blog@sha256:0489a1d6d719d30f4f971ae4f0f0f5e668ec5c43525f120acc09ec4a48fb7ec4
        livenessProbe:
          httpGet:
            path: /aboutme
            port: 8080
            scheme: HTTP
        name: workload
        readinessProbe:
          httpGet:
            path: /aboutme
            port: 8080
            scheme: HTTP
          successThreshold: 1
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

