apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-ui
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: blog-ui
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1665655182168905604"
    kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/making/build-service@sha256:f8dbbf8fa654c1731e039671a6683b97d3e4a2cd8344e9e99409cad8ecaf5f95
          top_layer: sha256:d10fcfd222e42332f995be30faf8856758b34ce68e864bf2206d87bf3f1a7108
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/deprecation-warnings
            version: 0.0.1
          - id: paketo-buildpacks/ca-certificates
            version: 3.4.0
          - id: tanzu-buildpacks/node-engine
            version: 0.13.0
          - id: tanzu-buildpacks/yarn
            version: 0.6.2
          - id: tanzu-buildpacks/yarn-install
            version: 0.7.4
          - id: tanzu-buildpacks/node-module-bom
            version: 0.3.2
          - id: tanzu-buildpacks/node-run-script
            version: 0.3.3
          - id: tanzu-buildpacks/yarn-start
            version: 0.3.3
          - id: paketo-buildpacks/image-labels
            version: 4.3.0
        inspect-image.buildpacks.io/run-image: ghcr.io/making/build-service@sha256:f8dbbf8fa654c1731e039671a6683b97d3e4a2cd8344e9e99409cad8ecaf5f95
        inspect-image.opencontainers.org/source: main/e4b8545441be6df44e2f592ff303d06d2957282d
        kapp.k14s.io/disable-original: ""
        kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-ui;carto.run/v1alpha1
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blog-ui
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: blog-ui
        kapp.k14s.io/app: "1665655182168905604"
        kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/blog-ui-blog@sha256:6fa70532abe0013c80334e2ad0c66cb06a2eb08ebfbcdc265883ea4ad402ce71
        name: workload
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

