apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-ui
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: blog-ui
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-ui
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/categolj/blog-ui?sub_path=/
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: registry.tanzu.vmware.com/build-service-dependency-updater/package-repo@sha256:6a86ef616d05dfc911c3f31b74f5c9b7017ea204f7b2aa909d0695def3bcc96d
          top_layer: sha256:8a1efd296ec5a8414c098ca0eed86325dd411e2b390700c5deeeb565547ec9f8
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/ca-certificates
            version: 3.7.0
          - id: tanzu-buildpacks/node-engine
            version: 2.2.5
          - id: tanzu-buildpacks/yarn
            version: 1.3.1
          - id: tanzu-buildpacks/yarn-install
            version: 1.3.8
          - id: tanzu-buildpacks/node-run-script
            version: 1.1.4
          - id: tanzu-buildpacks/yarn-start
            version: 1.2.9
          - id: tanzu-buildpacks/image-labels
            version: 4.6.0
        inspect-image.buildpacks.io/run-image: registry.tanzu.vmware.com/build-service-dependency-updater/package-repo@sha256:39452a0b4274e2b848c1f9f2e62d7048d1a0d6b1df9b4b1857b9e24c20c53c9a
        inspect-image.opencontainers.org/source: main@sha1:550ecfa15c48ccec2b0941993611afd9ac3633e8
        kapp.k14s.io/disable-original: ""
        kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-ui;carto.run/v1alpha1
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blog-ui
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: blog-ui
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/blog-ui-blog@sha256:5c648520341ef14b0ddd974f882c614ab0c95b2dc3c24cccc2c2166427215eac
        livenessProbe:
          httpGet:
            path: /aboutme
            port: 8080
            scheme: HTTP
        name: workload
        readinessProbe:
          httpGet:
            path: /aboutme
            port: 8080
            scheme: HTTP
          successThreshold: 1
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

