apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-ui
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: blog-ui
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1672995247146136642"
    kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    app.kubernetes.io/component: run
    carto.run/workload-name: blog-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/making/build-service@sha256:4ad9babcb718243b0dbdb29e8b3e1d474eafd6edc20e73a2a09dfde213d5fdcf
          top_layer: sha256:2dccd34d83ce1fcec8a5f20f06f0963d059264297222d1480a70c0d6645c88a1
        inspect-image.buildpacks.io/buildpacks: |-
          - id: paketo-buildpacks/ca-certificates
            version: 3.5.1
          - id: tanzu-buildpacks/node-engine
            version: 1.2.0
          - id: tanzu-buildpacks/yarn
            version: 1.1.1
          - id: tanzu-buildpacks/yarn-install
            version: 1.0.0
          - id: tanzu-buildpacks/node-module-bom
            version: 0.3.4
          - id: tanzu-buildpacks/node-run-script
            version: 1.0.1
          - id: tanzu-buildpacks/yarn-start
            version: 1.0.2
          - id: paketo-buildpacks/image-labels
            version: 4.4.0
        inspect-image.buildpacks.io/run-image: ghcr.io/making/build-service@sha256:e7ed7f534dce188a9dad9b4c6500d2bdc0fde73d1afb6043e3d6d72c02de7888
        inspect-image.opencontainers.org/source: main/c1a7f9f1d8a793d7303f9b773cc3b80f25110792
        kapp.k14s.io/disable-original: ""
        kapp.k14s.io/identity: v1;blog/carto.run/Workload/blog-ui;carto.run/v1alpha1
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blog-ui
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: blog-ui
        kapp.k14s.io/app: "1672995247146136642"
        kapp.k14s.io/association: v1.0ba63a416d64128605b90e7ad1328294
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/blog-ui-blog@sha256:798bb87d7bdc1e97665c48502cb1cf057880693e153a7fa9093338631cd3e2c0
        livenessProbe:
          httpGet:
            path: /aboutme
            port: 8080
            scheme: HTTP
        name: workload
        readinessProbe:
          httpGet:
            path: /aboutme
            port: 8080
            scheme: HTTP
          successThreshold: 1
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

