apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: cronjob-demo-otel-java-agent
  annotations:
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: cronjob-demo
    apps.tanzu.vmware.com/workload-type: cronjob
    app.kubernetes.io/component: run
    carto.run/workload-name: cronjob-demo
spec:
  name: otel-java-agent
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: otel-java-agent
  workload:
    apiVersion: batch/v1
    kind: CronJob
    name: cronjob-demo

