apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: note-api
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: note-api
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1673586328584986961"
    kapp.k14s.io/association: v1.f2bab8a28f3035fb38c00b9be169bab1
    app.kubernetes.io/component: run
    carto.run/workload-name: note-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 3.0.3
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/spring-boot-actuator-probes
          spring-boot-convention/app-live-view-appflavour-check
          spring-boot-convention/app-live-view-connector-boot
          spring-boot-convention/app-live-view-appflavours-boot
          spring-boot-convention/service-intent-postgres
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/making/build-service@sha256:2102b927cd48b53fb4f438c374087280601ac60f877eeb61ef519effa358723b
          top_layer: sha256:dbf57a4163eceb8bfb3b1301b8bb9d0015be22af50a072e9ca7f6094e423ac8a
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/deprecation-warnings
            version: 0.0.3
          - id: paketo-buildpacks/ca-certificates
            version: 3.5.1
          - id: paketo-buildpacks/bellsoft-liberica
            version: 9.10.3
          - id: paketo-buildpacks/syft
            version: 1.10.1
          - id: paketo-buildpacks/maven
            version: 6.12.1
          - id: paketo-buildpacks/executable-jar
            version: 6.5.0
          - id: paketo-buildpacks/apache-tomcat
            version: 7.11.1
          - id: paketo-buildpacks/liberty
            version: 3.3.0
          - id: paketo-buildpacks/dist-zip
            version: 5.4.0
          - id: paketo-buildpacks/spring-boot
            version: 5.22.1
          - id: paketo-buildpacks/jattach
            version: 1.2.0
          - id: paketo-buildpacks/image-labels
            version: 4.3.0
        inspect-image.buildpacks.io/run-image: ghcr.io/making/build-service@sha256:2102b927cd48b53fb4f438c374087280601ac60f877eeb61ef519effa358723b
        inspect-image.opencontainers.org/source: main/6996ce649ae656fcb2ef02282417ca28678710ff
        kapp.k14s.io/disable-original: ""
        kapp.k14s.io/identity: v1;note/carto.run/Workload/note-api;carto.run/v1alpha1
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
        services.conventions.carto.run/postgres: postgresql/42.5.4
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: note-api
        apps.tanzu.vmware.com/auto-configure-actuators: "true"
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: note-api
        conventions.carto.run/framework: spring-boot
        kapp.k14s.io/app: "1673586328584986961"
        kapp.k14s.io/association: v1.f2bab8a28f3035fb38c00b9be169bab1
        services.conventions.carto.run/postgres: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.path: actuator
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: note-api
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -XX:ReservedCodeCacheSize=32M -Xss512k -Dfile.encoding="UTF-8" -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details="always" -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include="*" -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s" -Duser.timezone="Asia/Tokyo"
        - name: ENTRY_APIURL
          value: ${k8s.bindings.note-config.entry-api-url}
        - name: ENTRY_CLIENTID
          value: ${k8s.bindings.note-config.entry-api-client-id}
        - name: ENTRY_CLIENTSECRET
          value: ${k8s.bindings.note-config.entry-api-client-secret}
        - name: RSA_PRIVATEKEY
          value: file:/bindings/note-config/rsa-private-key.pem
        - name: RSA_PUBLICKEY
          value: file:/bindings/note-config/rsa-public-key.pem
        - name: BPL_JVM_THREAD_COUNT
          value: "28"
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            secretKeyRef:
              key: otel-trace-service-name
              name: otel-config
        - name: SPRING_DATASOURCE_HIKARI_DATASOURCEPROPERTIES_SSLFACTORY
          value: org.postgresql.ssl.DefaultJavaSSLFactory
        - name: SPRING_SENDGRID_APIKEY
          value: ${k8s.bindings.note-config.sendgrid-api-key}
        - name: MANAGEMENT_TRACING_PROPAGATION_TYPE
          value: B3
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: otel-trace-endpoint
              name: otel-config
        - name: INFO_ENV_HOSTNAME
          value: ${HOSTNAME}
        - name: INFO_ENV_K_SERVICE
          value: ${K_SERVICE}
        - name: INFO_ENV_K_CONFIGURATION
          value: ${K_CONFIGURATION}
        - name: INFO_ENV_K_REVISION
          value: ${K_REVISION}
        image: ghcr.io/making/supply-chain/note-api-note@sha256:da79191b4277d0efa78c63d67b4dd324e2cec5bdfe37d86297b09fb9b028e514
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources:
          limits:
            memory: 416Mi
          requests:
            memory: 416Mi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

