apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: survey-survey-db
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
    kapp.k14s.io/disable-original: ""
    kapp.k14s.io/identity: v1;jsug/carto.run/Workload/survey;carto.run/v1alpha1
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: survey
    apps.tanzu.vmware.com/auto-configure-actuators: "false"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    kapp.k14s.io/app: "1677893433487879435"
    kapp.k14s.io/association: v1.ff9d87024c634aa58170fc7501617d25
    app.kubernetes.io/component: run
    carto.run/workload-name: survey
spec:
  name: survey-db
  service:
    apiVersion: v1
    kind: Secret
    name: survey-db
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: survey

