apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-db
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: backup-db
    apps.tanzu.vmware.com/auto-configure-actuators: "false"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: cronjob
    kapp.k14s.io/app: "1673062250001482428"
    kapp.k14s.io/association: v1.4e043a1fa1e762f9e99e68cc4f600214
    app.kubernetes.io/component: run
    carto.run/workload-name: backup-db
spec:
  schedule: 0 15 * * ?
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: backup-db
        apps.tanzu.vmware.com/auto-configure-actuators: "false"
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: cronjob
        carto.run/workload-name: backup-db
        conventions.carto.run/framework: spring-boot
        kapp.k14s.io/app: "1673062250001482428"
        kapp.k14s.io/association: v1.4e043a1fa1e762f9e99e68cc4f600214
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.path: actuator
        tanzu.app.live.view.application.actuator.port: "8080"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: backup-db
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            boot.spring.io/version: 3.0.6
            conventions.carto.run/applied-conventions: |-
              appliveview-sample/app-live-view-appflavour-check
              inspect-image-convention/buildpacks
              inspect-image-convention/base-image
              inspect-image-convention/run-image
              inspect-image-convention/source
              spring-boot-convention/auto-configure-actuators-check
              spring-boot-convention/spring-boot
              spring-boot-convention/spring-boot-actuator
              spring-boot-convention/app-live-view-appflavour-check
              spring-boot-convention/app-live-view-connector-boot
              spring-boot-convention/app-live-view-appflavours-boot
            developer.conventions/target-containers: workload
            inspect-image.buildpacks.io/base-image: |-
              reference: ghcr.io/making/stack-base-jammy-postgresql-client@sha256:40636af7d82e3f4e2d8fe6d8070aa3231bc0c6dd16eb9ed9ffe51a6d87d84606
              top_layer: sha256:eca5bdf29142a5ee0575c7a931bbab606b61f15ab142362a043619bdf46ffead
            inspect-image.buildpacks.io/buildpacks: |-
              - id: paketo-buildpacks/ca-certificates
                version: 3.6.0
              - id: paketo-buildpacks/bellsoft-liberica
                version: 9.11.0
              - id: paketo-buildpacks/syft
                version: 1.10.1
              - id: paketo-buildpacks/maven
                version: 6.13.0
              - id: paketo-buildpacks/executable-jar
                version: 6.6.2
              - id: paketo-buildpacks/apache-tomcat
                version: 7.12.1
              - id: paketo-buildpacks/liberty
                version: 3.5.0
              - id: paketo-buildpacks/dist-zip
                version: 5.5.2
              - id: paketo-buildpacks/spring-boot
                version: 5.23.0
              - id: paketo-buildpacks/image-labels
                version: 4.4.1
            inspect-image.buildpacks.io/run-image: ghcr.io/making/stack-base-jammy-postgresql-client:run@sha256:241bedd4bbc991a22773f79ee64f30ea3815c31de8195810dea23d5583f726ec
            inspect-image.opencontainers.org/source: main/e90ae51506ee0352633068b94b575c8aaed85cf4
            kapp.k14s.io/disable-original: ""
            kapp.k14s.io/identity: v1;blog/carto.run/Workload/backup-db;carto.run/v1alpha1
          labels:
            app.kubernetes.io/component: run
            app.kubernetes.io/part-of: backup-db
            apps.tanzu.vmware.com/auto-configure-actuators: "false"
            apps.tanzu.vmware.com/has-tests: "true"
            apps.tanzu.vmware.com/workload-type: cronjob
            carto.run/workload-name: backup-db
            conventions.carto.run/framework: spring-boot
            kapp.k14s.io/app: "1673062250001482428"
            kapp.k14s.io/association: v1.4e043a1fa1e762f9e99e68cc4f600214
            tanzu.app.live.view: "true"
            tanzu.app.live.view.application.actuator.path: actuator
            tanzu.app.live.view.application.actuator.port: "8080"
            tanzu.app.live.view.application.flavours: spring-boot
            tanzu.app.live.view.application.name: backup-db
        spec:
          containers:
          - env:
            - name: JAVA_TOOL_OPTIONS
              value: -Dmanagement.health.probes.enabled="false"
            - name: BPL_JVM_THREAD_COUNT
              value: "8"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: access_key
                  name: backup-s3
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: access_secret
                  name: backup-s3
            - name: S3_HOSTNAME
              valueFrom:
                secretKeyRef:
                  key: host
                  name: backup-s3
            - name: S3_BUCKET
              value: pg-dump-to-s3
            - name: PGDUMP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: blog-db
            - name: PGDUMP_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: blog-db
            - name: PGDUMP_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: blog-db
            - name: PGDUMP_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: blog-db
            - name: PGDUMP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: blog-db
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: otel-trace-endpoint
                  name: otel-config
            image: ghcr.io/making/supply-chain/backup-db-blog@sha256:43b45415ef7ae7d6b15214bb659575910a0ad66c7f58891a69ed4ae173b2227a
            name: workload
            resources: {}
            securityContext:
              runAsUser: 1000
          serviceAccountName: default
          restartPolicy: Never

