apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-python
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: hello-python
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: cronjob
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-python
spec:
  schedule: '* * * * ?'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello-python
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: cronjob
        carto.run/workload-name: hello-python
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            conventions.carto.run/applied-conventions: |-
              appliveview-sample/app-live-view-appflavour-check
              inspect-image-convention/buildpacks
              inspect-image-convention/base-image
              inspect-image-convention/run-image
              inspect-image-convention/source
              spring-boot-convention/auto-configure-actuators-check
              spring-boot-convention/app-live-view-appflavour-check
            developer.conventions/target-containers: workload
            inspect-image.buildpacks.io/base-image: |-
              reference: ghcr.io/making/build-service@sha256:7439c23b8bfe069b8e73b1486041d78852ec2a0ccd1c4d4715089dd4630de4b2
              top_layer: sha256:2d8fc429b90a5667d94370598fe77e5df0bf9f2e12a679cb50fd8dd2d5389395
            inspect-image.buildpacks.io/buildpacks: |-
              - id: tanzu-buildpacks/deprecation-warnings
                version: 0.0.3
              - id: paketo-buildpacks/ca-certificates
                version: 3.5.1
              - id: tanzu-buildpacks/cpython
                version: 1.8.2
              - id: tanzu-buildpacks/pip
                version: 0.16.4
              - id: tanzu-buildpacks/pip-install
                version: 0.5.7
              - id: tanzu-buildpacks/python-start
                version: 0.10.3
              - id: paketo-buildpacks/procfile
                version: 5.5.0
              - id: paketo-buildpacks/image-labels
                version: 4.4.0
            inspect-image.buildpacks.io/run-image: ghcr.io/making/build-service@sha256:b1415ad3a283e2f18ecbd0e6027602ee21a3a4280e40f0ce7f4e86bb9fe4eff1
            inspect-image.opencontainers.org/source: main/dac0187e86dc00a21db42c09c012019d130779c2
          labels:
            app.kubernetes.io/component: run
            app.kubernetes.io/part-of: hello-python
            apps.tanzu.vmware.com/has-tests: "true"
            apps.tanzu.vmware.com/workload-type: cronjob
            carto.run/workload-name: hello-python
        spec:
          containers:
          - image: ghcr.io/making/supply-chain/hello-python-demo@sha256:511abc94b8f504b9a14936553aa7f9d5e99d34de9d2e239bcb6d935f22cb7360
            name: workload
            resources: {}
            securityContext:
              runAsUser: 1000
          serviceAccountName: default
          restartPolicy: Never

