apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-python
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: hello-python
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: cronjob
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-python
spec:
  schedule: '* * * * ?'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello-python
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: cronjob
        carto.run/workload-name: hello-python
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            conventions.carto.run/applied-conventions: |-
              appliveview-sample/app-live-view-appflavour-check
              inspect-image-convention/buildpacks
              inspect-image-convention/base-image
              inspect-image-convention/run-image
              inspect-image-convention/source
              spring-boot-convention/auto-configure-actuators-check
              spring-boot-convention/app-live-view-appflavour-check
            developer.conventions/target-containers: workload
            inspect-image.buildpacks.io/base-image: |-
              reference: ghcr.io/making/build-service@sha256:4ad9babcb718243b0dbdb29e8b3e1d474eafd6edc20e73a2a09dfde213d5fdcf
              top_layer: sha256:2dccd34d83ce1fcec8a5f20f06f0963d059264297222d1480a70c0d6645c88a1
            inspect-image.buildpacks.io/buildpacks: |-
              - id: paketo-buildpacks/ca-certificates
                version: 3.5.1
              - id: tanzu-buildpacks/cpython-lite
                version: 1.8.2
              - id: tanzu-buildpacks/pip-lite
                version: 0.16.4
              - id: tanzu-buildpacks/pip-install
                version: 0.5.7
              - id: tanzu-buildpacks/python-start
                version: 0.10.3
              - id: paketo-buildpacks/procfile
                version: 5.5.0
              - id: paketo-buildpacks/image-labels
                version: 4.4.0
            inspect-image.buildpacks.io/run-image: ghcr.io/making/build-service@sha256:4ad9babcb718243b0dbdb29e8b3e1d474eafd6edc20e73a2a09dfde213d5fdcf
            inspect-image.opencontainers.org/source: main/dac0187e86dc00a21db42c09c012019d130779c2
          labels:
            app.kubernetes.io/component: run
            app.kubernetes.io/part-of: hello-python
            apps.tanzu.vmware.com/has-tests: "true"
            apps.tanzu.vmware.com/workload-type: cronjob
            carto.run/workload-name: hello-python
        spec:
          containers:
          - image: ghcr.io/making/supply-chain/hello-python-demo@sha256:9a3c7090da7fb8714a240b056fbe5ae5642299c06a4692641742ad6464437ed0
            name: workload
            resources: {}
            securityContext:
              runAsUser: 1000
          serviceAccountName: default
          restartPolicy: Never

