apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ssr-react-spring-boot-graalvm-js
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: ssr-react-spring-boot-graalvm-js
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: ghcr.io/making/ssr-react-spring-boot-graalvm-js
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/is-prometheus-enabled-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: index.docker.io/paketobuildpacks/run-jammy-tiny@sha256:82c53abe6acb87c85d7b67b3666d2c03a98dfe218548df33fb8c5393b5edb147
          top_layer: sha256:f5268b9e3c58a2fd49939abb4baca3ad16b8046a9064b6ce67b439fcc8840cc4
        inspect-image.buildpacks.io/buildpacks: |-
          - id: paketo-buildpacks/image-labels
            version: 4.6.0
          - id: paketo-buildpacks/procfile
            version: 5.8.0
        inspect-image.buildpacks.io/run-image: index.docker.io/paketobuildpacks/run-jammy-tiny:latest
        inspect-image.opencontainers.org/source: main@sha1:d4043f7b876b11dcf27ea68331d18518717feafb
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: run
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: ssr-react-spring-boot-graalvm-js
    spec:
      containers:
      - env:
        - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
          value: http://otel-collector.opentelemetry.svc.cluster.local:4318/v1/traces
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "1.0"
        image: ghcr.io/making/ssr-react-spring-boot-graalvm-js@sha256:a4ec4cad6884a2bd213630b4a7ce700c4844c6adf310330770021a2db96b840e
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

