apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-nodejs
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: hello-nodejs
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-nodejs
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/making/hello-nodejs?sub_path=/
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: registry.tanzu.vmware.com/build-service-dependency-updater/package-repo@sha256:39452a0b4274e2b848c1f9f2e62d7048d1a0d6b1df9b4b1857b9e24c20c53c9a
          top_layer: sha256:7df3b3428053a16ccec55e82c4a988b585bdf0e30f3da554c8b365bc31df7df3
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/ca-certificates
            version: 3.7.0
          - id: tanzu-buildpacks/node-engine
            version: 2.2.5
          - id: tanzu-buildpacks/npm-install
            version: 1.3.5
          - id: tanzu-buildpacks/node-start
            version: 1.2.10
          - id: tanzu-buildpacks/npm-start
            version: 1.1.7
          - id: tanzu-buildpacks/image-labels
            version: 4.6.0
        inspect-image.buildpacks.io/run-image: registry.tanzu.vmware.com/build-service-dependency-updater/package-repo@sha256:39452a0b4274e2b848c1f9f2e62d7048d1a0d6b1df9b4b1857b9e24c20c53c9a
        inspect-image.opencontainers.org/source: master@sha1:c05aa5983dd4ba9de688720efbe319fc89a175e4
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello-nodejs
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hello-nodejs
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/hello-nodejs-demo@sha256:980e283479623d79ddb3db6c11d3decac6a0b992de39edf8f9daeb6a4b11cba9
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

