apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-nodejs
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: hello-nodejs
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-nodejs
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/making/hello-nodejs?sub_path=/
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: registry.tanzu.vmware.com/build-service-dependency-updater/package-repo@sha256:4db5880b6e8322b21f5e1107a8a2d3dcf57bde60e4523ef2784d8cdddb725f98
          top_layer: sha256:10a85fe66612bd28e9cc515d2e53d6011248c6dbcf08a58d56abdec96ede4415
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/ca-certificates
            version: 3.7.0
          - id: tanzu-buildpacks/node-engine
            version: 2.2.5
          - id: tanzu-buildpacks/npm-install
            version: 1.3.5
          - id: tanzu-buildpacks/node-start
            version: 1.2.10
          - id: tanzu-buildpacks/npm-start
            version: 1.1.7
          - id: tanzu-buildpacks/image-labels
            version: 4.6.0
        inspect-image.buildpacks.io/run-image: registry.tanzu.vmware.com/build-service-dependency-updater/package-repo@sha256:4db5880b6e8322b21f5e1107a8a2d3dcf57bde60e4523ef2784d8cdddb725f98
        inspect-image.opencontainers.org/source: master@sha1:c05aa5983dd4ba9de688720efbe319fc89a175e4
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello-nodejs
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hello-nodejs
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/hello-nodejs-demo@sha256:ab96f3678debb9b6d424d051116fed8b814d8225c288e504e31ed4472d1b03c5
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

