apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-go
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: hello-go
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-go
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/GoogleCloudPlatform/golang-samples?sub_path=run/helloworld
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/making/tanzu-application-platform/full-deps-package-repo@sha256:363a8d83a865e1091eb480e85ca5b1eb89006d77bd0896438d47e2534122924f
          top_layer: sha256:e93857364431c04243df85536d44892efaa881110e2e2f9443d1b8a0b0658752
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/ca-certificates
            version: 3.7.0
          - id: tanzu-buildpacks/go-dist
            version: 2.4.7
          - id: tanzu-buildpacks/go-mod-vendor
            version: 1.1.7
          - id: tanzu-buildpacks/go-build
            version: 2.1.7
          - id: tanzu-buildpacks/image-labels
            version: 4.6.0
        inspect-image.buildpacks.io/run-image: ghcr.io/making/tanzu-application-platform/full-deps-package-repo@sha256:363a8d83a865e1091eb480e85ca5b1eb89006d77bd0896438d47e2534122924f
        inspect-image.opencontainers.org/source: main@sha1:28d24e441ba22ea9dfcb2fd5ad40ffd8881fa0dd
        instrumentation.opentelemetry.io/inject-go: opentelemetry/default
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: /layers/tanzu-buildpacks_go-build/targets/bin/helloworld
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello-go
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hello-go
    spec:
      containers:
      - env:
        - name: NAME
          value: TAP
        image: ghcr.io/making/supply-chain/hello-go-demo@sha256:2643d7cbbf20c327f2bdcdd508147008ca53545690b7271bb767c1ae7af56ec4
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

