apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-fly
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: hello-fly
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-fly
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          inspect-image-convention/buildpacks
          inspect-image-convention/base-image
          inspect-image-convention/run-image
          inspect-image-convention/source
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        inspect-image.buildpacks.io/base-image: |-
          reference: ghcr.io/making/build-service@sha256:2102b927cd48b53fb4f438c374087280601ac60f877eeb61ef519effa358723b
          top_layer: sha256:dbf57a4163eceb8bfb3b1301b8bb9d0015be22af50a072e9ca7f6094e423ac8a
        inspect-image.buildpacks.io/buildpacks: |-
          - id: tanzu-buildpacks/deprecation-warnings
            version: 0.0.2
          - id: paketo-buildpacks/ca-certificates
            version: 3.4.0
          - id: tanzu-buildpacks/node-engine-lite
            version: 0.16.0
          - id: tanzu-buildpacks/npm-install
            version: 0.8.8
          - id: tanzu-buildpacks/node-module-bom-lite
            version: 0.3.3
          - id: tanzu-buildpacks/node-start
            version: 0.4.6
          - id: tanzu-buildpacks/npm-start
            version: 0.5.3
          - id: paketo-buildpacks/image-labels
            version: 4.3.0
        inspect-image.buildpacks.io/run-image: ghcr.io/making/build-service@sha256:2102b927cd48b53fb4f438c374087280601ac60f877eeb61ef519effa358723b
        inspect-image.opencontainers.org/source: main/c14f44e2e27a066f6a370d600d60fb6ef197b69c
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello-fly
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hello-fly
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/hello-fly-demo@sha256:071770ad12c8633aac6411625d5f7735662f7cc6b30b1bbe069996f5b06c92e7
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

