apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tanzu-java-web-app
  annotations:
    kubernetes.io/ingress.class: contour
    cert-manager.io/cluster-issuer: "letsencrypt"
    kapp.k14s.io/change-rule: "upsert after upserting Services"
  labels: 
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app
    
spec:
  tls:
    - secretName: tanzu-java-web-app-tls
      hosts:
      - tanzu-java-web-app.run.lime.maki.lol
  rules:
  - host: tanzu-java-web-app.run.lime.maki.lol
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: tanzu-java-web-app
            port:
              number: 8080

