#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Deployment"}), expects="0+"
---
spec:
  selector:
    matchLabels:
      #@overlay/remove missing_ok=True
      kapp.k14s.io/app: ""
      #@overlay/remove missing_ok=True
      kapp.k14s.io/association: ""
  template:
    metadata:
      labels:
        #@overlay/remove missing_ok=True
        kapp.k14s.io/app: ""
        #@overlay/remove missing_ok=True
        kapp.k14s.io/association: ""
#@overlay/match by=overlay.subset({"kind": "Service"}), expects="0+"
---
spec:
  selector:
    #@overlay/remove missing_ok=True
    kapp.k14s.io/app: ""
    #@overlay/remove missing_ok=True
    kapp.k14s.io/association: ""

