#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Deployment"}), expects="0+"
---
spec:
  #@overlay/match-child-defaults missing_ok=True
  selector:
    matchLabels:
      #@overlay/remove
      kapp.k14s.io/app: ""
      #@overlay/remove
      kapp.k14s.io/association: ""
  #@overlay/match-child-defaults missing_ok=True
  template:
    metadata:
      labels:
        #@overlay/remove
        kapp.k14s.io/app: ""
        #@overlay/remove
        kapp.k14s.io/association: ""
#@overlay/match by=overlay.subset({"kind": "Service"}), expects="0+"
---
spec:
  #@overlay/match-child-defaults missing_ok=True
  selector:
    #@overlay/remove
    kapp.k14s.io/app: ""
    #@overlay/remove
    kapp.k14s.io/association: ""

