apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
  - path: [spec, replicas]
    type: copy
    sources: [existing, new]
    resourceMatchers:
    - apiVersionKindMatcher:
        kind: Deployment
        apiVersion: apps/v1

